[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hieroglyphic-pattern-analyzer"
version = "0.1.0"
description = "Hieroglyphic Pattern Analyzer"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
include = ["src*"]